name: replace-delimited-content
description: Replace content between delimiters in a file
inputs:
  file:
    required: true
  start:
    required: true
  end:
    required: true
  new_content_file:
    required: true
outputs:
  changed:
    description: 'true if file would change'
runs:
  using: node20
  main: dist/index.js
