name: Bulk Repository Changes

permissions:
  contents: write       # For CODEOWNERS file operations
  pull-requests: write  # For creating pull requests

on:
  workflow_dispatch:
    inputs:
      operation:
        description: 'Operation to perform'
        required: true
        type: choice
        options:
          - 'disable-wiki'
          - 'add-changelog-codeowners'
          - 'add-changelog-file'
          - 'update-swagger-links'
          - 'update-swagger-links-releases'
        default: 'disable-wiki'
      
      dry_run:
        description: 'Run in dry-run mode (no actual changes)'
        required: true
        type: boolean
        default: true
      
      # Repository Category Selection
      include_sandbox_repos:
        description: 'Include Sandbox API Repositories'
        required: false
        type: boolean
        default: true
      
      include_incubating_repos:
        description: 'Include Incubating API Repositories'
        required: false
        type: boolean
        default: true
      
      include_working_group_repos:
        description: 'Include Working Group Repositories'
        required: false
        type: boolean
        default: true
      
      include_other_repos:
        description: 'Include Other Repositories'
        required: false
        type: boolean
        default: true
      
      repository_filter:
        description: 'Repository name pattern (leave empty for all repos)'
        required: false
        type: string
        default: ''
      
      exclude_repos:
        description: 'Comma-separated list of repos to exclude'
        required: false
        type: string
        default: 'Governance,.github'
      
      commit_strategy:
        description: 'How to apply file changes (only applies to file-based operations)'
        required: false
        type: choice
        options:
          - 'pull-request'
          - 'direct-with-warning'
        default: 'pull-request'

jobs:
  get-repositories:
    runs-on: ubuntu-latest
    outputs:
      repositories: ${{ steps.get-repos.outputs.repositories }}
      total_count: ${{ steps.get-repos.outputs.total_count }}
    steps:
      - name: Get organization repositories
        id: get-repos
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.CAMARA_TOKEN || secrets.GITHUB_TOKEN }}
          script: |
            const org = 'camaraproject';
            const filterPattern = '${{ github.event.inputs.repository_filter }}';
            const excludeRepos = '${{ github.event.inputs.exclude_repos }}'.split(',').map(r => r.trim()).filter(r => r);
            
            // Category selection inputs
            const includeSandbox = ${{ fromJson(github.event.inputs.include_sandbox_repos) }};
            const includeIncubating = ${{ fromJson(github.event.inputs.include_incubating_repos) }};
            const includeWorkingGroup = ${{ fromJson(github.event.inputs.include_working_group_repos) }};
            const includeOther = ${{ fromJson(github.event.inputs.include_other_repos) }};
            
            console.log(`Getting repositories for organization: ${org}`);
            console.log(`Include categories: Sandbox=${includeSandbox}, Incubating=${includeIncubating}, WorkingGroup=${includeWorkingGroup}, Other=${includeOther}`);
            
            let allRepos = [];
            let page = 1;
            
            while (true) {
              const response = await github.rest.repos.listForOrg({
                org: org,
                type: 'all',
                sort: 'name',
                per_page: 100,
                page: page
              });
              
              if (response.data.length === 0) break;
              allRepos = allRepos.concat(response.data);
              page++;
            }
            
            // Function to categorize repository based on topics
            function categorizeRepository(topics) {
              if (topics.includes('sandbox-api-repository')) {
                return 'sandbox';
              } else if (topics.includes('incubating-api-repository')) {
                return 'incubating';
              } else if (topics.includes('workinggroup')) {
                return 'working-group';
              } else {
                return 'other';
              }
            }
            
            // Filter repositories based on criteria and categories
            let filteredRepos = [];
            let categoryCounts = { sandbox: 0, incubating: 0, 'working-group': 0, other: 0 };
            
            for (const repo of allRepos) {
              if (repo.archived) continue;
              if (excludeRepos.includes(repo.name)) continue;
              if (filterPattern && !repo.name.includes(filterPattern)) continue;
              
              const category = categorizeRepository(repo.topics || []);
              categoryCounts[category]++;
              
              let includeThisRepo = false;
              switch (category) {
                case 'sandbox': includeThisRepo = includeSandbox; break;
                case 'incubating': includeThisRepo = includeIncubating; break;
                case 'working-group': includeThisRepo = includeWorkingGroup; break;
                case 'other': includeThisRepo = includeOther; break;
              }
              
              if (includeThisRepo) {
                filteredRepos.push(repo);
              }
            }
            
            const repositories = filteredRepos.map(repo => ({
              name: repo.name,
              full_name: repo.full_name,
              default_branch: repo.default_branch,
              category: categorizeRepository(repo.topics || [])
            }));
            
            console.log(`Selected ${repositories.length} repositories for processing`);
            core.setOutput('repositories', JSON.stringify(repositories));
            core.setOutput('total_count', repositories.length);

  execute-changes:
    needs: get-repositories
    if: fromJson(needs.get-repositories.outputs.total_count) > 0
    strategy:
      matrix:
        repository: ${{ fromJson(needs.get-repositories.outputs.repositories) }}
      max-parallel: 5
      fail-fast: false
    uses: ./.github/workflows/project-admin-repository-worker.yml
    with:
      repository_name: ${{ matrix.repository.name }}
      repository_full_name: ${{ matrix.repository.full_name }}
      default_branch: ${{ matrix.repository.default_branch }}
      operation: ${{ github.event.inputs.operation }}
      dry_run: ${{ fromJson(github.event.inputs.dry_run) }}
      commit_strategy: ${{ github.event.inputs.commit_strategy }}
    secrets:
      CAMARA_TOKEN: ${{ secrets.CAMARA_TOKEN }}

  collect-results:
    needs: [get-repositories, execute-changes]
    if: always() && fromJson(needs.get-repositories.outputs.total_count) > 0
    runs-on: ubuntu-latest
    steps:
      - name: Download all result artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: result-*
          path: artifacts/
          merge-multiple: true

      - name: Collect and summarize results
        uses: actions/github-script@v7
        with:
          script: |
            const repositories = JSON.parse('${{ needs.get-repositories.outputs.repositories }}');
            const operation = '${{ github.event.inputs.operation }}';
            const dryRun = ${{ fromJson(github.event.inputs.dry_run) }};
            const commitStrategy = '${{ github.event.inputs.commit_strategy }}' || 'N/A';
            
            console.log('Collecting results from artifacts...');
            
            const fs = require('fs');
            const path = require('path');
            
            // Emoji mapping for result types (centralized here)
            const emojiMap = {
              'success': '✅',
              'no-change': '📊', 
              'warning': '⚠️',
              'would-action': '🧪',
              'error': '❌'
            };
            
            // Function to determine if result requires attention
            function requiresAttention(resultType) {
              return ['warning', 'error'].includes(resultType);
            }
            
            let results = [];
            let resultTypeCounts = {};
            
            // Read result files from artifacts
            try {
              const artifactsDir = 'artifacts';
              if (fs.existsSync(artifactsDir)) {
                const files = fs.readdirSync(artifactsDir);
                console.log(`Found ${files.length} result files`);
                
                for (const file of files) {
                  if (file.endsWith('.json')) {
                    try {
                      const filePath = path.join(artifactsDir, file);
                      const resultData = JSON.parse(fs.readFileSync(filePath, 'utf8'));
                      
                      // Use the generalized result fields from worker
                      const resultType = resultData.result_type || 'unknown';
                      const details = resultData.details || 'No details available';
                      const emoji = emojiMap[resultType] || '❓';
                      const requiresAttentionFlag = requiresAttention(resultType);
                      
                      resultTypeCounts[resultType] = (resultTypeCounts[resultType] || 0) + 1;
                      
                      const repoInfo = repositories.find(r => r.name === resultData.repository);
                      const category = repoInfo ? repoInfo.category : 'unknown';
                      
                      // Add PR/commit links to details if available
                      let detailsWithLinks = details;
                      if (resultData.pr_number && resultData.pr_url) {
                        detailsWithLinks += ` [PR #${resultData.pr_number}](${resultData.pr_url})`;
                      }
                      
                      results.push({
                        repository: resultData.repository,
                        category: category,
                        result_type: resultType,
                        details: detailsWithLinks,
                        emoji: emoji,
                        requires_attention: requiresAttentionFlag,
                        operation_status: resultData.operation_status || resultType,
                        action_taken: resultData.action_taken || 'unknown',
                        pr_url: resultData.pr_url || '',
                        pr_number: resultData.pr_number || '',
                        commit_sha: resultData.commit_sha || ''
                      });
                      
                    } catch (parseError) {
                      console.log(`Error parsing ${file}: ${parseError.message}`);
                      // Add error entry for failed parsing
                      const repoName = file.replace(/^result-/, '').replace(/\.json$/, '');
                      results.push({
                        repository: repoName,
                        category: 'unknown',
                        result_type: 'error',
                        details: `Failed to parse result file: ${parseError.message}`,
                        emoji: '❌',
                        requires_attention: true,
                        operation_status: 'parse-error',
                        action_taken: 'failed',
                        pr_url: '',
                        pr_number: '',
                        commit_sha: ''
                      });
                      resultTypeCounts['error'] = (resultTypeCounts['error'] || 0) + 1;
                    }
                  }
                }
              }
            } catch (error) {
              console.log(`Error reading artifacts: ${error.message}`);
            }
            
            console.log(`Collected ${results.length} results`);
            
            // Generate report
            const timestamp = new Date().toISOString();
            const totalRepos = repositories.length;
            
            const reportLines = [
              '# CAMARA Bulk Repository Changes - Execution Report',
              '',
              `**Execution Time:** ${timestamp}`,
              `**Operation:** ${operation}`,
              `**Commit Strategy:** ${commitStrategy}`,
              `**Mode:** ${dryRun ? 'DRY RUN' : 'LIVE EXECUTION'}`,
              `**Total Repositories:** ${totalRepos}`,
              '',
              '## Result Type Summary',
              '',
              '| Result Type | Count | Percentage |',
              '|-------------|-------|------------|'
            ];
            
            for (const [resultType, count] of Object.entries(resultTypeCounts)) {
              const percentage = totalRepos > 0 ? ((count / totalRepos) * 100).toFixed(1) : '0.0';
              const emoji = emojiMap[resultType] || '❓';
              reportLines.push(`| ${emoji} ${resultType} | ${count} | ${percentage}% |`);
            }
            
            reportLines.push('');
            reportLines.push('## Repository Results');
            reportLines.push('');
            reportLines.push('| Repository | Category | Result | Details |');
            reportLines.push('|------------|----------|--------|---------|');
            
            // Sort results: attention-required first, then by repository name
            results.sort((a, b) => {
              if (a.requires_attention && !b.requires_attention) return -1;
              if (!a.requires_attention && b.requires_attention) return 1;
              return a.repository.localeCompare(b.repository);
            });
            
            for (const result of results) {
              reportLines.push(`| ${result.repository} | ${result.category} | ${result.emoji} ${result.result_type} | ${result.details} |`);
            }
            
            reportLines.push('');
            
            // Add attention section if there are items requiring attention
            const attentionItems = results.filter(r => r.requires_attention);
            if (attentionItems.length > 0) {
              reportLines.push('## Items Requiring Attention');
              reportLines.push('');
              for (const item of attentionItems) {
                reportLines.push(`- **${item.repository}**: ${item.details}`);
              }
              reportLines.push('');
            }
            
            reportLines.push('---');
            reportLines.push('*Generated by CAMARA project-admin bulk workflow*');
            
            const markdownReport = reportLines.join('\n');
            
            // Create CSV and JSON data
            let csvLines = ['Repository,Category,Result Type,Details,Operation Status,Action Taken,PR Number,PR URL,Commit SHA,Requires Attention'];
            for (const result of results) {
              csvLines.push(`"${result.repository}","${result.category}","${result.result_type}","${result.details}","${result.operation_status}","${result.action_taken}","${result.pr_number}","${result.pr_url}","${result.commit_sha}","${result.requires_attention}"`);
            }
            const csvData = csvLines.join('\n');
            
            const jsonReport = {
              metadata: {
                timestamp: timestamp,
                operation: operation,
                commit_strategy: commitStrategy,
                dry_run: dryRun,
                total_repositories: totalRepos
              },
              summary: {
                result_types: resultTypeCounts,
                items_requiring_attention: attentionItems.length
              },
              results: results
            };
            
            // Write files
            if (!fs.existsSync('results')) {
              fs.mkdirSync('results');
            }
            
            fs.writeFileSync('results/bulk-changes-report.md', markdownReport);
            fs.writeFileSync('results/bulk-changes-results.csv', csvData);
            fs.writeFileSync('results/bulk-changes-data.json', JSON.stringify(jsonReport, null, 2));
            
            console.log('✅ Created result files');
            
            // Add summary to job summary
            core.summary.addRaw(markdownReport);
            await core.summary.write();
            
            console.log(`📊 Results summary completed - processed ${totalRepos} repositories`);
            
            // Log summary stats
            console.log('\n=== Summary Statistics ===');
            for (const [resultType, count] of Object.entries(resultTypeCounts)) {
              console.log(`${resultType}: ${count}`);
            }
            if (attentionItems.length > 0) {
              console.log(`\n⚠️ ${attentionItems.length} items require attention`);
            }

      - name: Upload results artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bulk-changes-results-${{ github.run_number }}
          path: results/
          retention-days: 30

  summary:
    needs: [get-repositories, execute-changes, collect-results]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Final summary
        uses: actions/github-script@v7
        with:
          script: |
            const totalRepos = ${{ needs.get-repositories.outputs.total_count }};
            const operation = '${{ github.event.inputs.operation }}';
            const dryRun = ${{ fromJson(github.event.inputs.dry_run) }};
            const executionResult = '${{ needs.execute-changes.result }}';
            const collectionResult = '${{ needs.collect-results.result }}';
            
            let summary = `## Bulk Repository Changes Summary\n\n`;
            summary += `**Operation**: ${operation}\n`;
            summary += `**Mode**: ${dryRun ? 'DRY RUN' : 'LIVE'}\n`;
            summary += `**Total Repositories**: ${totalRepos}\n`;
            summary += `**Execution Status**: ${executionResult}\n`;
            summary += `**Results Collection**: ${collectionResult}\n\n`;
            
            if (totalRepos === 0) {
              summary += `⚠️ No repositories matched the selection criteria.\n`;
            } else {
              summary += `📊 **Detailed results available in downloadable artifacts**\n\n`;
              
              if (dryRun) {
                summary += `🧪 **This was a dry run** - no actual changes were made.\n`;
              } else {
                summary += `✅ **Live execution completed**.\n`;
              }
            }
            
            core.summary.addRaw(summary);
            await core.summary.write();